sudo: required

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build --tag septimalmind/izumi-env:latest --tag septimalmind/izumi-env:${TRAVIS_BRANCH} --tag septimalmind/izumi-env:${TRAVIS_COMMIT} izumi-env
  - docker push septimalmind/izumi-env:latest
  - docker push septimalmind/izumi-env:${TRAVIS_BRANCH}
  - docker push septimalmind/izumi-env:${TRAVIS_COMMIT}
